spring:
  application:
    name: tanzu-java-web-app
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
#      probes:
#        add-additional-paths: true
      show-details: always

#  server:
#    port: 8181
#  health:
#    probes:
#      enabled: true
